CLASS zcl_bp_sopyay_m DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_sopyay_m.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_bp_sopyay_m IMPLEMENTATION.
ENDCLASS.
